COMMIT;
--- DROP ---
DROP TABLE TODO;
DROP SEQUENCE SEQ_TODO;
--- CREATE ---
CREATE SEQUENCE SEQ_TODO NOCACHE NOCYCLE;
CREATE TABLE TODO
(
        ID          NUMBER          PRIMARY KEY
        ,CONTENT    VARCHAR2(60)    NOT NULL
        ,COMPLETE   CHAR(1)         DEFAULT 'N' CHECK (COMPLETE IN('Y','N'))
        ,CREATE_AT  DATE            DEFAULT  SYSDATE
)
;
-- TODO 더미 데이터 --
INSERT INTO TODO (ID, CONTENT) VALUES (SEQ_TODO.NEXTVAL, '주말에 그림 그리기');
INSERT INTO TODO (ID, CONTENT) VALUES (SEQ_TODO.NEXTVAL, '독서 1시간 하기');
INSERT INTO TODO (ID, CONTENT) VALUES (SEQ_TODO.NEXTVAL, '기타 연습하기');
INSERT INTO TODO (ID, CONTENT) VALUES (SEQ_TODO.NEXTVAL, '사진 찍으러 나가기');
INSERT INTO TODO (ID, CONTENT) VALUES (SEQ_TODO.NEXTVAL, '일기 쓰기');

-- 조회 -- 
SELECT 
    ID
    ,CONTENT
    ,COMPLETE
    ,CREATE_AT
FROM TODO
;
-- 단건 조회 --
SELECT
    ID
    ,CONTENT
    ,COMPLETE
    ,CREATE_AT
FROM TODO
WHERE ID = 1
;
-- 수정 --
UPDATE TODO
SET
    CONTENT = '고양이 목욕시켜주기'
WHERE ID = 1; 

-- 논리 삭제 --
UPDATE TODO
SET
    COMPLETE = 'Y'
WHERE ID = 1